# Generated by Django 3.0.7 on 2020-08-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_autoparts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=30, null=True)),
                ('rank_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='RequestUpdate',
            new_name='RequestStatus',
        ),
        migrations.RenameField(
            model_name='requeststatus',
            old_name='request_order',
            new_name='rs_item',
        ),
        migrations.RenameField(
            model_name='requeststatus',
            old_name='status',
            new_name='rs_status',
        ),
        migrations.CreateModel(
            name='PurchaseUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu_itemprice', models.IntegerField(blank=True, null=True)),
                ('pu_japandeliveryfee', models.IntegerField(blank=True, null=True)),
                ('pu_internationaldeliveryfee', models.IntegerField(blank=True, null=True)),
                ('pu_total', models.IntegerField(blank=True, null=True)),
                ('pu_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce_autoparts.OrderRequest')),
            ],
        ),
    ]
