# Generated by Django 3.0.7 on 2020-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_autoparts', '0002_auto_20200816_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_remark', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='purchaseupdate',
            old_name='pu_internationaldeliveryfee',
            new_name='pu_deliveryfee',
        ),
        migrations.RenameField(
            model_name='purchaseupdate',
            old_name='pu_japandeliveryfee',
            new_name='pu_intdeliveryfee',
        ),
        migrations.RenameField(
            model_name='purchaseupdate',
            old_name='pu_total',
            new_name='pu_rank',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='rank_price',
            new_name='r_aprice',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='rank',
            new_name='r_title',
        ),
        migrations.AddField(
            model_name='rank',
            name='r_bprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
